### ISSUE TITLE
To improve use policy

### ISSUE THREAD

**Issue by ictsozo02** [City-of-Kobe/website-policy#2]
Please give us some advice about what to do to improve use policy.
利用規約を改善するためのご意見をお願いします。

**Comment by hkwi** [comment]
[オープンデータガイド第1版](http://www.opendata.gr.jp/news/1407/140731_000866.php)も合わせて読んで、[data.go.jp](http://www.data.go.jp/terms-of-use/terms-of-use/) をベースにしているのだと読み取りました。

オープンデータガイド第1版にある、利用ルールの雛形を「そのまま」使うのが良いと思います。「条項」と「解説やお願い」は明確に分けるべきです。また特に第6条は意味不明で積極的に削除すべきだと思います。

**Comment by hkwi** [comment]
そのまま使ったほうが良い、という理由についてもう少し補足させてください。

まずガイドラインにある雛形のほうが、より練られて文言が精査された規約になっているという点。データ相互運用性のためには、できるだけ他のデータと共通のライセンスで運用されているほうが良いという点。活用上、ライセンスの互換性の確認には、改変が少なければ少ないほうが良いです。また共通のライセンスを使ったほうが、ノウハウの蓄積が適切に行われます（条項に問題が出てきた場合の発見が早い）。つまり各オープンデータ発行元が協力して、定常的にメンテナンスされている共通のライセンスを採用するのがベストだと思います。これは市が主体的にライセンス自体のメンテナンスを行うべき（予算を使うべき）という意味では「なく」、メンテナンスされているライセンスを活用するのが良いと思います。そういう意味では、必ずしもガイドラインにあるものでなくても良いと思います。

**Comment by ictsozo03** [comment]
雛形のままが良いとのご意見についてありがとうございました。
雛形と完全に一致させるのか、あるいは雛形に近づけるのかについては検討いたします。
さて、こちらからもお聞きしたいのですが、どの部分が「解説やお願い」というように捉えらえましたか。また、第6条について、どのように意味不明なのかお聞かせください。我々は、第6条について、リンクであったとしても具体的な名称などは挙げられませんが不適切な団体と関わりがあると疑われるような状況にはしておけないという意味合いで設定しております。

**Comment by hkwi** [comment]
6条に関しては、[wikipedia　リンクフリー](https://ja.wikipedia.org/wiki/%E3%83%AA%E3%83%B3%E3%82%AF%E3%83%95%E3%83%AA%E3%83%BC) を参照するとご理解いただけるかと思いますが、ナンセンスです。リンク元が不適切な団体かどうかを判断するべきではないと考えます。

**Comment by ismail-a** [comment]
上記の議論を見てきて僕も第6条については不要だと思います。
「ただし、各情報においてリンクの制限等の注記がある場合にはこの限りではありません。」これは非オープンデータに対する無断2次利用の予防だと思いますが、そういったものは著作権で保護されているので書くまでもないと思います。
不適切な団体と関わりがあると疑われるということについては、片方向のリンクでは関わりがあるとは捉われないと思います。
wikipediaのリンクフリーのリンク集にある[奥村先生の記事](http://oku.edu.mie-u.ac.jp/~okumura/compedu/?%A5%EA%A5%F3%A5%AF%A4%CB%B5%F6%B2%C4%A4%CF%C9%D4%CD%D7%A4%C7%A4%B9)にもある通り、リンクフリーはWebの本質を理解していないことを公言しているようなものです。Webページはまだ著作物が混ざっている点において多少の理解は得られているますが、オープンデータとなると恥ずかしいことになるかもしれません。

**Comment by hkwi** [comment]
わたしはオープンソースのプログラムを配布しますが、ライセンスは良く使われてこなれているものをそのまま使います。追加条項は設けません。これはOSSを結合して使えるようにし、安心して流通に乗せられるようにするためです。ライセンスが明示されていないものは流通させられません（[参考](http://opensource.srad.jp/story/12/12/04/0141252)）。

法律家ではありませんが、詳しい議論をするためにはCCのライセンス条文を参照せざるを得ません。が少し楽をしますと、FAQの解説に次の記述があります。「[クリエイティブ・コモンズの利用許諾書は、原則として法的効力があります](http://creativecommons.jp/faq/#b15)」また[ライセンスによって付与される利用許諾受領者の権利の行使を変更又は制限するような条件を提案したり課したりする行為](http://creativecommons.jp/faq/detail/#h10)は禁止されています。実のところCCに追加条項を付けるのは難しく、えてして（ライセンスを行う側が）CCのライセンスを破ってしまいます。破れている場合はもはやCCとは呼べず、すなわち、流通できないものになります。これはルールなので厳密で、オープンソースどうしの[組み合わせ](http://creativecommons.jp/faq/#c13)にも影響します。

個人的な意見としては、ガイドラインの雛形は追加条項がついているのは、そもそも良くない（危ない）です。例えば 5 条にある準拠法の記述は、そもそもの日本版CCに入っている記述で、単に冗長な上、ライセンスする側もされる側もその冗長な部分をチェックしないといけないというデメリットがあります。

ガイドラインの雛形を見ると、（条項は法的効力を持ちますが）雛形の最後の（利用にあたってのお願いと御注意）は（おそらく敢えて）条項になっていません。神戸市オープンデータ利用規約の第7条は条項にすべきではなく、お願いの分類するものだと思います。

神戸市オープンデータ利用規約の第6条は、CCを壊すはずです。いろいろな意味で、これは削除するべきだと思います。

**Comment by ictsozo03** [comment]
リンクのWebにおける概念については理解できました。そもそもWebを利用する前提としてリンクは自由であり、自由であるが故にどのような団体がリンクを貼ったとしても、Web利用者の共通意識として、各利用者の関係性について疑うことは当然ないということ。また、そもそも扱っているものがオープンデータで誰もが二次利用可能であり、利用者を限定しないことを鑑みると、リンクを気にすること自体不自然であるということですね。

今までの話を派生させると、CCライセンスを用いるのであれば、CCライセンスの利用許諾だけで著作権の保護や免責事項を規定できており、個別に自治体が利用規約を作成あるいは“雛形”を利用すると、CCライセンスと各規約とで二重に規約を設定してしまう状況や齟齬を生じさせてしまうため、CCライセンスの利用許諾のみを明示あるいは参照する方がいいという理解でいいでしょうか。

**Comment by hkwi** [comment]
はい。誤解なく正しく意図が伝わったようで、ありがとうございます。 :-)

付け加えるならば、CCの適用範囲を明示する、というのはCCでも要求されていることなので、そこをハッキリさせると適用しやすくなるかと思います。

**Comment by ictsozo03** [comment]
これまでの流れを受けて、利用規約案を変更してみました。ご意見・ご感想等ございましたらお願いいたします。

**Comment by ictsozo02** [comment]
ウェブサイト利用規約に統一するため、こちらはクローズします。
